#!/bin/bash
python feeder-paginator.py --crawl --bfolder Acer --folder phonesdata/gsmarena2 --struct acer-phones-59-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder alcatel --folder phonesdata/gsmarena2 --struct alcatel-phones-5-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Allview --folder phonesdata/gsmarena2 --struct allview-phones-88-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Amazon --folder phonesdata/gsmarena2 --struct amazon-phones-76-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Amoi --folder phonesdata/gsmarena2 --struct amoi-phones-28-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Apple --folder phonesdata/gsmarena2 --struct apple-phones-48-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Archos --folder phonesdata/gsmarena2 --struct archos-phones-90-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Asus --folder phonesdata/gsmarena2 --struct asus-phones-46-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder AT&T --folder phonesdata/gsmarena2 --struct at&t-phones-57-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Benefon --folder phonesdata/gsmarena2 --struct benefon-phones-15-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder BenQ --folder phonesdata/gsmarena2 --struct benq-phones-31-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder BenQ-Siemens --folder phonesdata/gsmarena2 --struct benq_siemens-phones-42-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Bird --folder phonesdata/gsmarena2 --struct bird-phones-34-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder BlackBerry --folder phonesdata/gsmarena2 --struct blackberry-phones-36-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder BLU --folder phonesdata/gsmarena2 --struct blu-phones-67-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Bosch --folder phonesdata/gsmarena2 --struct bosch-phones-10-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder BQ --folder phonesdata/gsmarena2 --struct bq-phones-108-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Casio --folder phonesdata/gsmarena2 --struct casio-phones-77-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Cat --folder phonesdata/gsmarena2 --struct cat-phones-89-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Celkon --folder phonesdata/gsmarena2 --struct celkon-phones-75-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Chea --folder phonesdata/gsmarena2 --struct chea-phones-24-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Coolpad --folder phonesdata/gsmarena2 --struct coolpad-phones-105-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Dell --folder phonesdata/gsmarena2 --struct dell-phones-61-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Emporia --folder phonesdata/gsmarena2 --struct emporia-phones-93-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Energizer --folder phonesdata/gsmarena2 --struct energizer-phones-106-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Ericsson --folder phonesdata/gsmarena2 --struct ericsson-phones-2-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Eten --folder phonesdata/gsmarena2 --struct eten-phones-40-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Fujitsu_Siemens --folder phonesdata/gsmarena2 --struct fujitsu_siemens-phones-50-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Garmin-Asus --folder phonesdata/gsmarena2 --struct garmin_asus-phones-65-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Gigabyte --folder phonesdata/gsmarena2 --struct gigabyte-phones-47-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Gionee --folder phonesdata/gsmarena2 --struct gionee-phones-92-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Google --folder phonesdata/gsmarena2 --struct google-phones-107-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Haier --folder phonesdata/gsmarena2 --struct haier-phones-33-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder HP --folder phonesdata/gsmarena2 --struct hp-phones-41-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder HTC --folder phonesdata/gsmarena2 --struct htc-phones-45-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Huawei --folder phonesdata/gsmarena2 --struct huawei-phones-58-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder i-mate --folder phonesdata/gsmarena2 --struct i_mate-phones-35-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder i-mobile --folder phonesdata/gsmarena2 --struct i_mobile-phones-52-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Icemobile --folder phonesdata/gsmarena2 --struct icemobile-phones-69-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Innostream --folder phonesdata/gsmarena2 --struct innostream-phones-29-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder iNQ --folder phonesdata/gsmarena2 --struct inq-phones-60-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Intex --folder phonesdata/gsmarena2 --struct intex-phones-102-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Jolla --folder phonesdata/gsmarena2 --struct jolla-phones-84-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Karbonn --folder phonesdata/gsmarena2 --struct karbonn-phones-83-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Kyocera --folder phonesdata/gsmarena2 --struct kyocera-phones-17-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Lava --folder phonesdata/gsmarena2 --struct lava-phones-94-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder LeEco --folder phonesdata/gsmarena2 --struct leeco-phones-109-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Lenovo --folder phonesdata/gsmarena2 --struct lenovo-phones-73-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder LG --folder phonesdata/gsmarena2 --struct lg-phones-20-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Maxon --folder phonesdata/gsmarena2 --struct maxon-phones-14-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Maxwest --folder phonesdata/gsmarena2 --struct maxwest-phones-87-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Meizu --folder phonesdata/gsmarena2 --struct meizu-phones-74-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Micromax --folder phonesdata/gsmarena2 --struct micromax-phones-66-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Microsoft --folder phonesdata/gsmarena2 --struct microsoft-phones-64-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Mitac --folder phonesdata/gsmarena2 --struct mitac-phones-25-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Mitsubishi --folder phonesdata/gsmarena2 --struct mitsubishi-phones-8-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Modu --folder phonesdata/gsmarena2 --struct modu-phones-63-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Motorola --folder phonesdata/gsmarena2 --struct motorola-phones-4-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder MWg --folder phonesdata/gsmarena2 --struct mwg-phones-56-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder NEC --folder phonesdata/gsmarena2 --struct nec-phones-12-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Neonode --folder phonesdata/gsmarena2 --struct neonode-phones-22-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder NIU --folder phonesdata/gsmarena2 --struct niu-phones-79-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Nokia --folder phonesdata/gsmarena2 --struct nokia-phones-1-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Nvidia --folder phonesdata/gsmarena2 --struct nvidia-phones-97-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder O2 --folder phonesdata/gsmarena2 --struct o2-phones-30-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder OnePlus --folder phonesdata/gsmarena2 --struct oneplus-phones-95-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Oppo --folder phonesdata/gsmarena2 --struct oppo-phones-82-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Orange --folder phonesdata/gsmarena2 --struct orange-phones-71-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Palm --folder phonesdata/gsmarena2 --struct palm-phones-27-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Panasonic --folder phonesdata/gsmarena2 --struct panasonic-phones-6-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Pantech --folder phonesdata/gsmarena2 --struct pantech-phones-32-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Parla --folder phonesdata/gsmarena2 --struct parla-phones-81-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Philips --folder phonesdata/gsmarena2 --struct philips-phones-11-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Plum --folder phonesdata/gsmarena2 --struct plum-phones-72-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Posh --folder phonesdata/gsmarena2 --struct posh-phones-101-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Prestigio --folder phonesdata/gsmarena2 --struct prestigio-phones-86-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder QMobile --folder phonesdata/gsmarena2 --struct qmobile-phones-103-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Qtek --folder phonesdata/gsmarena2 --struct qtek-phones-38-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Sagem --folder phonesdata/gsmarena2 --struct sagem-phones-13-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Samsung --folder phonesdata/gsmarena2 --struct samsung-phones-9-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Sendo --folder phonesdata/gsmarena2 --struct sendo-phones-18-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Sewon --folder phonesdata/gsmarena2 --struct sewon-phones-26-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Sharp --folder phonesdata/gsmarena2 --struct sharp-phones-23-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Siemens --folder phonesdata/gsmarena2 --struct siemens-phones-3-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Sonim --folder phonesdata/gsmarena2 --struct sonim-phones-54-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Sony --folder phonesdata/gsmarena2 --struct sony-phones-7-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Sony_Ericsson --folder phonesdata/gsmarena2 --struct sony_ericsson-phones-19-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Spice --folder phonesdata/gsmarena2 --struct spice-phones-68-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder T-Mobile --folder phonesdata/gsmarena2 --struct t_mobile-phones-55-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Tel.Me. --folder phonesdata/gsmarena2 --struct tel_me_-phones-21-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Telit --folder phonesdata/gsmarena2 --struct telit-phones-16-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Thuraya --folder phonesdata/gsmarena2 --struct thuraya-phones-49-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Toshiba --folder phonesdata/gsmarena2 --struct toshiba-phones-44-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Unnecto --folder phonesdata/gsmarena2 --struct unnecto-phones-91-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Vertu --folder phonesdata/gsmarena2 --struct vertu-phones-39-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder verykool --folder phonesdata/gsmarena2 --struct verykool-phones-70-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder vivo --folder phonesdata/gsmarena2 --struct vivo-phones-98-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder VK_Mobile --folder phonesdata/gsmarena2 --struct vk_mobile-phones-37-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Vodafone --folder phonesdata/gsmarena2 --struct vodafone-phones-53-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Wiko --folder phonesdata/gsmarena2 --struct wiko-phones-96-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder WND --folder phonesdata/gsmarena2 --struct wnd-phones-51-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder XCute --folder phonesdata/gsmarena2 --struct xcute-phones-43-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Xiaomi --folder phonesdata/gsmarena2 --struct xiaomi-phones-80-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder XOLO --folder phonesdata/gsmarena2 --struct xolo-phones-85-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Yezz --folder phonesdata/gsmarena2 --struct yezz-phones-78-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder Yota --folder phonesdata/gsmarena2 --struct yota-phones-99-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder YU --folder phonesdata/gsmarena2 --struct yu-phones-100-p --mfile missed-models-1.txt --start 2 --end 13 
python feeder-paginator.py --crawl --bfolder ZTE --folder phonesdata/gsmarena2 --struct zte-phones-62-p --mfile missed-models-1.txt --start 2 --end 13 
