# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchrock',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launchrock',
            name='name',
            field=models.CharField(default=b'user', max_length=255),
        ),
    ]
